os:
  - linux
  - osx
language: c
dist: xenial
osx_image: xcode11.6
sudo: required
env:
  - EMULATOR=klh10 BASICS=yes
install: sh -ex build/dependencies.sh install_${TRAVIS_OS_NAME:-linux}
script: make check-dirs all
notifications:
  email: lars@nocrew.org
